export const REQUEST_CSRF = 'REQUEST_CSRF';
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const REGISTER_PAGE_LOAD = "REGISTER_PAGE_LOAD";
export const SETTING_PAGE_LOAD = "SETTING_PAGE_LOAD";
export const SETTING_PAGE_UNLOAD = "SETTING_PAGE_UNLOAD";
export const ARTICLES_LOAD = "ARTICLES_LOAD";
export const ARTICLE_CREATED = "ARTICLE_CREATED";
export const ARTICLE_UPDATE = "ARTICLE_UPDATE";
export const ARTICLE_DELETED = "ARTICLE_DELETED";
export const MEDIA_DELETED = "MEDIA_DELETED";
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const UPLOAD_SETTING_PROGRESS = "UPLOAD_SETTING_PROGRESS";
export const TAGS_LOAD = "TAGS_LOAD";



export const SAVE_USER_INFO = "SAVE_USER_INFO";